---
abstract: 'Module that provides shortcuts to retrieve certain information'
author:
  - 'Kjetil Kjernsmo <kjetilk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  FindBin: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RDF-Helper-Properties
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Moose: 0
  RDF::Trine: 0.125
  Scalar::Util: 0
  namespace::autoclean: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.08
